# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Offloaded memory
email: ryan@tiqtech.com
description: >
  If I write it down here, I don't have to keep it in my head.
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "ryanjduffy.github.io" # the base hostname & protocol for your site
github_repo: blog
github_username: ryanjduffy
twitter_username: theryanjduffy
codepen_username: ryanjduffy
paginate: 10
excerpt_separator: <!--more-->

# Build settings
plugins:
  - jekyll-paginate
